### ISSUE TITLE
Singleton resource caching

### ISSUE THREAD

**Issue by stufisher** [ispyb/py-ispyb-ui#37]
Some resources are fetched as singletons, which means they dont have unique keys for the rest-hooks cache. Need to figure out a way to either auto expire these, or key them, or do something else.

Resources such as
* auto processing statuses for the current dc page
* data for the session stat graphs

**Comment by ntucker** [comment]
Might this be applicable here? https://resthooks.io/rest/guides/network-transform#case-of-the-missing-id

Sometimes you don't even need an entity too, and using https://resthooks.io/rest/api/RestEndpoint without a schema is sufficient. Especially if you're not using more than one of the [CRUD methods](https://resthooks.io/rest/api/createResource#members)

**Comment by stufisher** [comment]
Yes indeed, thats the route i started taking, thanks. For some of these resources its possible to construct meaningful pks from the existing response which can then key the resources:
https://github.com/ispyb/py-ispyb-ui/pull/38/files#diff-9307fb31c77942988b9746f61aa1df5434cc14095027159ac8129ed924986624R15
